AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: API Lambda Demo.
Resources:
  apilambdademo:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: 'A demo lambda'
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::293899812389:role/service-role/sam-local-demo'
      Events:
        GetDemo:
          Type: Api
          Properties:
            Path: /demo
            Method: get
        PostDemo:
          Type: Api
          Properties:
            Path: /demo
            Method: post
        PutDemoId:
          Type: Api
          Properties:
            Path: '/demo/{id}'
            Method: put
        GetDemoId:
          Type: Api
          Properties:
            Path: '/demo/{id}'
            Method: get